apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - audacity/ks.yaml
  - adguard-gui/ks.yaml
  - authelia/ks.yaml
  # - backuppc/ks.yaml
  # - beets/ks.yaml
  # - cloudflareddns/ks.yaml
  # - code-server/ks.yaml
  # - dashy/ks.yaml
  # - deluge/ks.yaml
  # - dev-mongodb/ks.yaml
  # - dev-postgresql/ks.yaml
  # - dev-jbsoum-org/ks.yaml
  # - docker/ks.yaml
  # - docuseal/ks.yaml
  - emby/ks.yaml
  # - emulatorjs/ks.yaml
  - firefox-syncserver/ks.yaml
  - gitea/ks.yaml
  # - homarr-v1/ks.yaml
  - homepage/ks.yaml
  - icloudpd/ks.yaml
  # - invidious/ks.yaml
  - jellyseerr/ks.yaml
  - jellyfin/ks.yaml
  # - joplin-server/ks.yaml
  # - kopia/ks.yaml
  - kubernetes-dashboard/ks.yaml
  # - laravel/ks.yaml
  # - libreddit/ks.yaml
  - lidarr/ks.yaml
  - lldap/ks.yaml
  # - metube/ks.yaml
  # - navidrome/ks.yaml
  # - netbootxyz/ks.yaml
  - nextcloud/ks.yaml
  # - nitter/ks.yaml
  # - odoo/ks.yaml
  # - onlyoffice-document-server/ks.yaml
  # - pgadmin/ks.yaml
  - protonmail-bridge/ks.yaml
  - prowlarr/ks.yaml
  # - proxmox-backup-server/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  # - readarr/ks.yaml
  # - renovate/ks.yaml
  # # - scrutiny/ks.yaml
  # # - searxng/ks.yaml
  - sonarr/ks.yaml
  - truenas-gui/ks.yaml
  # - vaultwarden/ks.yaml
  # - vocechat-server/ks.yaml
  # # - watchyourlan/ks.yaml
  # # - whoogle/ks.yaml
  # -  proxmox-backup-server/ks.yaml
  - voice-ai-gui/ks.yaml
  - homarr/ks.yaml
  - wg-easy/ks.yaml
