apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:f2+E7sopN/y2rSIORlwdUVTzqFDmhYFOPUQxiaa3GkFBOh/bj99DcbD52vVcfOQAbzl0s85aWGPPvpRNekSxKbJXZ/AEH1KXwyn6m+eveL0am2hihhypwbgp6yB2ZQ95lj3BZiVM/Kd5/PWcRvAmF5ka0zIWi96tNCE8Ljxqaoaufdxdc41jx4dtcJN1bWLPvmLfFVJNlFPTs6WN2QgNe/sFDVA6PkGpceRigrCO0n9aGR89WWdYcMEy8zdp4BQzuVazUtJunWeGeLpSe5i1UtOTv0b4Ky3zuByQefRx4nxge8rf+wfF/KP8X+NSqNnFmTtcEL8Nx8oTWr4Ryy+szpXOFI2jS819Ybvg8IsdBBVD18SiZ4epVZUpzcTSWfGp,iv:VqotQv2idkfNtwzzkmHQyTE+ZWjdGcLxTIoY/INiJ3w=,tag:dWLbRzpviqQUFmN5wJDFvg==,type:str]
    identity.pub: ENC[AES256_GCM,data:QMXYPP+6VlGXA88S8oD8OsbIeCeq/DXc/tstANIZWeNW/1Ws/Lo2edI2PWyXI0zBs4Ah8RLhWQD4x/oZGUc8QqfdixZGVdLtxIu2khfeAYqFsVwWuhnn4jwki/6Ik2bLQCtzdgbzzP97GrWfQOZc5csoBZjb5au3m8myq6oiNzsq4S6xMbMGdCNwBEwix56M5j1cX+zEC+huJK/vg/4nH/4v8safBX175nSzhOiJYdSJAbwt7FAxSydcHm+dIn7IVW0GqOG3Qm2MnZH9XA==,iv:4Od4qMs/PwUpwoHf8t+wH5FZ12lLKzf0e3nnMqYlyIc=,tag:fjLmrUrfZEtEkMsqY9m/qw==,type:str]
    known_hosts: ENC[AES256_GCM,data:x4PLDxuN0HP4a/XebdgpudwaDQl3zy8Q0EK8v6mllMiI61NhLFSjtZi1Za2WLCzdaLBHpEIN7kofAltKVm6rG+rvPQ7wvDvmAYQtSasw0/IXoc9T6jO7ZwdmXJZGF1ZXfRUWdJ1D5nyfV4A8DJn6qEPjjAzGsAN/uSfrD2USMIfDDrZ0KL5MRMlu838a1YyeO9InjQLJ2iodX9gOEC98QAZGZSUVNjTpJ6Bw,iv:1Z9onCyOE8iKUD6JBo46aEj8XcnkpG2Abe0+rucCcnc=,tag:K7Agv0sIjB1qV0Yfv6hDFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OFhFY05hdVlyNVU2NE5N
            dlZtSGFQUDcraDV0UEJIZEpvK0F1Q2NsZmlJCmtvd2x2aERsWWxBbDRNWDRGSUhX
            bWp0UVd6NGRDZ2x2ZHBIZUZyT1hUK3cKLS0tIE1zZGhFa1dTSlBaWWFlU3NCNk5h
            M081TmpQb0cwcHpGVTVLYWZyaHRzaWsKM1lXiHpcNSUzW1LunA7lJoyRLniBsWKs
            eFtBc6Jbl8XZJq7UNkixIIbQXdGRQ+72jEn5nbTP0nsZMISH2x+zXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T14:56:43Z"
    mac: ENC[AES256_GCM,data:/SN7N8gy+UU81mfyBr82Snrzm5eSUhQ1hHJKrwz5rXmyxIsr0SOd2YqkRYCVnUsNbRuAg6HRFVWe0W5hh+wsKwC79N1Jv+tfo4dGJYNRIMMi0lEMH+ee4o4xz34VTBxdwpDDez78kdHetRAMWnnJwjX3AWOkGFkRTCobyVscUKs=,iv:wHZecuF+J63EVa4LQvCov/YOq3lafadeFCLGYJZcTEc=,tag:Fmzdra84MtGCM7KH1XPFFA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
