apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z3fQdpz9tFu88SErqjg9cSP/f4mRIx1RTWGeF5pY7/Eyxl/tOLesBlrfqimj5th9+gsd2y/+IhJjamGWRdJb8VSvtJkps2+UVbPNRTmr0yxecHY5LwkjOOthWsfZACQ5Fe6Ky2Iyny8atebY2Y9KypriQKj0qbTt3KLkfrg4HfBT4qi3FtUGNkC9j2v3roHfx3B4GhUiwWh053AnhBFw8RU7KlWjp+k+80QGHZ+AuJ9U3F1BZHAkMsrcNKhB4pWmn36/bL1IRekciDVp9RFeJjrPTWmXUZkj71WIwZGR1R4tSSOpthUMYFMmb0MoqAh+2hbNL37BgYaoCwsjI7dDqXIkagX86vH0Q3SX691/TtabuebAeUwDTXYV5yZpHq/I,iv:2uI1tT5pGQ/caV1KTG7Pl4jpzaB2AN1VscQ5rV0N2xw=,tag:RB0JPPSizQVyz6ty4ypfjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:9I57cihj+ZdvKvRlm0mybBdqtByltw5fWSY5vU8ztTInlvH8dqmrzsigIfAxNhI5TxmDAZXYp2KN20cEJXzYuxKqqXHVyONcvbFI434YfxpHHID00EFxS2iRyoq9RClkjKb5/qPMe6S+XL2Dlvwb3CZlqORMz9Cav3cslYXL382AFAO3rJAr5nC1elDU7KffwBpAzqSMCrDgxUvtLrMawZU8LDpZsQ9xicgTB8AXAzPOmT3kEeRpQlwqJh0ntxa3b996eGFfXYgnQaHwBg==,iv:uTWVOYbUcW3BU2M0QEGVUDs9wdjEDjnABpT502rJoUA=,tag:I4KilsErjLSkZAux+RCbqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:E6leYdJ2KnnbIf0Kh58j8SaZzw64CX5npPg8H4Z2HlJ6mINZUmievKwY+acumG4BH4rYdCY1msp064WB/bE2RCv5kvkyIM6sW7k5XdGfaPpKgtAPasC0qtKSH5mP9xKFG1J+GquNYueWPithvOhVgYKemyZOoXPB1nkdGuCXV+Vium0ecAcgNzLv6YX+NvVxz2YyALwpfl7EWRJUiXkWkRyr3gwSqhB3J6Of,iv:QoYcG6qY5rJJ15XqtkASx2eJA1SvDr+1UEi+s0bFWaI=,tag:5I0IUrvNrnqeEtvESDtWnA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNTkzbEdzVWUwQTcyWno2
            dGx5U2NRMWxyTnlEUUYrM2JQMW8wMGJFanpvCkpzdUxLTDlKb0R4aWdsR09Semx4
            T2c2d2JEVndsR1M1QWd4MXJMZDk2cFEKLS0tIEQwdjZlRFZRSGgrTUFlalI3S3lY
            YXI5R25vNjJXY2J4UWU2T1VPTmZhemMKc5ibvN72xL/xcQycmCD5r8heZGmwRLQr
            mg1a90esYFJeG0Uuk5M8ICzgsirOEnSXgvzuRbQImbYXkDe0FNgK8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T17:31:07Z"
    mac: ENC[AES256_GCM,data:v7plMBez/0Mb4KTr22bMYgpGujPkY4gtLq2lF/GVAqhjAKgeyeJQuAhHAGyQdiaK+vH3QvvQf+tZzv6+Rh4xy9aEoC9RSkbdmQsKKy5rsHxv9PrTE4Lhae384FMEOEYfw9lrj7L9dNcp0GB2x84u3yn372LQ/hm8nT4KcJI0ZjY=,iv:i6q+dElpZQPPU3EIa8xVugO5KWptnFlTXWdAUwb41o0=,tag:Mk++38qgMQ6zxh75VWK6Iw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
