apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1iEO2zaer9hF24/Ch7PmxQVJVKXPUy35VhWcQSsGkG7I4aR6bKe0q5+kbwMbBjy5eZqHtleIHNFQnULaGN0xM/eBghTOAvCMW5/NB6/YMXh/2CG95ZIxeRe6mb2zrBEHDGmXyJvtefmzxvxDbu+G+tpbCjiv3iJ+vzJpXLxb25FvOJxHXt38zGQmvBxllfveQTWGGboJSBvkz61BlOGm+YRuGFlTA+sbuychUzfr1JAbeMXcdzqRV1+qUq9SYnI9ZSOfSKD6tBtLWsshPr91PR7ImF15v8mFrRMB5d3lC3m78vANoH3/amj4um8rKFe/3RKcJ1KAbTJ29Z/0q3IEEZXYrYl7VDS/7TKEdb48GoKMvRQWCIix1dq5WLyPu32X,iv:n8K7vudtaz+8JugGF0SwI5t16aeOVBxk5P7rPrfxUfk=,tag:1y7VRBa032B6rhs1/dq1OA==,type:str]
    identity.pub: ENC[AES256_GCM,data:5+X58ZSecZqrPd3/t+zdJZcImn+OMYKDBgb3wHw8cRo+JpyfCl7ZTQ+AZ36qzhoeK1wk3areXUsfe7WQENRglIxLoBZAI5x6lkAl3VNPH7SC9FzZ92YJdbFjjK08AfzE63eGuc3uQHG0tteBtQHnXt3pLGRuci+k9zxWKwWMqmZvAlkz560/4LejU0oHyu8ghdh+KmzPKeKU4ALIuHGvARLAiZIVZrK7R/qZG7nN/EBQDXf8f/G55k9qTKbqo14CnQSsMZcJCXK/Bb84pA==,iv:88E2cv9CABuO661H+d+gCSLZyeESnEIePGmL7vx1JMw=,tag:TEp5YF5Sbml1++BgKQhWJA==,type:str]
    known_hosts: ENC[AES256_GCM,data:34687LR6QG3JsUdzYGNYeylENij0B4nIGXUT80K35xoamapLB0xqkLVOtWe1afny8+qOpw+fzkeVy9rM7B1FpOenjdDoKQq/n5ViXsGRV8P/0j20HAoITw4hWn2/ivcmmCYxKqDvJcvqAcWMp0VoNeGddeQUyUpAGvmbzU4voNqfqYCBa/Q5UveoumbzwdJIsaJAr0xuT5ZQqtRkJdPTdhJUBPfXhsJBTIsi,iv:6TG4GJeIgE3KmxDLuWPUiHwSbIJvbad98/RFq/FYqdA=,tag:U7zj/F9ssocjAo4DxsIHVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT2g4WXNBUEgwZGQrdmtp
            QnRRS2RieVJsTE5IRzA1Q0U3aE8zZEkwNjE0CkhnMEN2MEliVkMxd1ErTWg4TzRR
            THpQbjdDL1dYKzI0ay9GSXRRT1JsRzAKLS0tIFFNSSt6TndQN1VvWjNwSm90NmZZ
            MTExUGtTKys5VEFvYmJOUHRrTURjRDgKC0ZKN/5zjgqXwBZDCKHtyDHDXUfAa7BH
            n1DtCGKfWLfe8LhKsAU6YyN41LbGt63egATuMcvYW+/nnsJ2dxzSRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T08:35:58Z"
    mac: ENC[AES256_GCM,data:n+4RfUBYGmsHLFYc0frSHsKF/n0GWKAMzlw4TgpJqNM3kWaJXyJa/D2h5ZZk/fG38gVfSvJU3IGKfJokB6nkRNxMazKgPPEaqiEYCnJnSAeU31SRsPu7LYC2hDYSqq3m3kSxCcAPdTVkLu0AHZ/qpYksvvkL2bRvFTNk62OiJ+M=,iv:sE8jB5lBlNQlY6Ch8ki5EeiHyOc+cLege9SrZPR/cNw=,tag:YUUx676ocSTftfh8Ca/7wg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
