apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VLou7L4o23WB71FL7uvEM08xGhuHSLYABLbgdCIenaKUmCE59Grxiqf+eN5DN1ZMu3HlSikG2ifwqoFKROUy1S2X/zlNuCCMK1Gs4FoAFkbcYqcxY8mDHtzL5MPQ6wfb1/B75y6tKa8Gg2c7ayAjN3GHWc6qsD2eloNvVlKCsqaeTbpqlyZhWs8fGMzspBWYuLBVSP0WLtEhcXTS1SMxNgPHFmdDYZED3IHDpKhglcY6f+4UQ54NNDTSao1sExj4CgQOc6dXTHPe+Zj7qOz/7UDcEtc8YZAMrdIur66ywdr+HqKfjGB8k2TS00kDRmZxKXf3IVWBNuv5iSCwmq1oe65zwvmv/PUzRwHQ0EYJTIxvrr5AjTl8nH/mg0YHR6Fb,iv:H1PgWZyJ29sNYnPWktwE/Stkv+gLgROIsZKkPHdGhRk=,tag:eN42sOkJF0nJUAnJcjdm3g==,type:str]
    identity.pub: ENC[AES256_GCM,data:GIxSCEsIUwcuthwL8wILGnH9nXl7p5pv4yOvYu2TfFMGIl1VzwamhyEEB0VfMujwyotMQLtyir04mocByxE0Zl3jPPqPWSKcU0KMEZjHzg+11XTLERbGhj066dJg6f12FEGtOZnYhjCwbGUivu9rrllLMYbcPLlcdRdOfCqjtPjh4PWpe/jiQ85V+Goc9g1KijfNoAY4JFtonxqzUsLgzD3rXJRQfL+EKb3y/fcT9WBEWhA0xKEkkA4qUwBdOtqlCcPfDV5bW4m9fRO0Pg==,iv:cwMOWvDWsqlOvI/oGJ2GNkgcdPDUCZFcOSmztKs+Sm4=,tag:XyXreH//GiPVdv6zZv5ZTA==,type:str]
    known_hosts: ENC[AES256_GCM,data:zWmwI8rc/r5vZLISYowVh0zKvh+wy6cdRQ7tKOABoL82VTpXW1LLyRG5SMYtf7fOpYYKrYoac8CJRLTR8sbyuVfNEJzstCvdnJ3BHLglXx6HqNuqX5PwOKI5H3s+cLfmAiwRbcw6uSTAHWBgu5urcWSdPWb5WfISGrDhnfQC5bYw80rNMT5a45ydPSk1vAn4N/bUaiKePWrqVy9vZ2cwEqIKThDN6zHAGJAP,iv:eZuBAkVA9ULFoUKyFzPcGQwZMSnLptm26UeeVQ+6dLI=,tag:FfBVXYw9AjJF2w+aXtliWg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdE44OHh5MWxSM0RwRVlv
            dllvM2VPcHJVand3aXo2c002N2h3M1lKMVdrCnlqRUhhSGxoS3V1STdVUlIyek1r
            REtnYzFHUzQrbHE4a0dnNFpYMHRUck0KLS0tIC9hdThlZ1RDK2NaQ1ZneWFnTFBN
            cFVaVVlEZEJWM01BZGY2WWNtZy9SbGcKqEnvyvNdsFnn+vTr7h7DorEm6yvwHjDK
            gaIb4SJgDjplykjI41XyN5ItfPDjZ332iygT9lJg+eiyAgmILO7LnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T16:52:31Z"
    mac: ENC[AES256_GCM,data:IcDT8zbN4sWwEoIOozAzH2iEmjpRDxrWZpJMv8mkP0Zo+c/vGjGQUqX5RqJIRY0oZN9MsaAbpp+dzDavS3NUvXlzk2oJ+l4z92UbcwWVCOfmexChr2YmiF43sNnLAS20nGv+NaPh2EESpozCfL/LRuf4pUqzmNPSVdLHiBc7Hoo=,iv:UZvS2e60pDvcvVNTf7kBNjAB/gRRAc3Ezc6yPhKlH6c=,tag:SPNi7ToIWRHo4ADz/BNSSA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
