apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:grW5RE2TjXjMJZhWEt1x/I0+nbx2k0AzJyCaM5x99Sw+mLIzC2I2nsjmpIW2kx9na7CCS2B5u+xsFAENRSKn+S623OhGZC0uY4SNd1F2Wl2ccPvtlh5d/W/fi1ztOnBeNXn1GZ28jUVwS6v5vA6nESNaFdsFpyLp4gxJaltVg0D8XwHYUcSzgdrRkCJ20/1iaP+NHs+UYZNIRtNAn6sAWaJILDSSSFtyKBb9q/a+k4YasuJu5MoYSY7m+y29oYWx1rFbXXW8t2hXncvCQX1Qm3m5mDg6zgx1v69xxxAW8uVYPgqzi8UHmzJFFhRMGyfGJu+dkq+zRj6qITJhE81tkuIy1acOfLk6eQ9/doaVILdEevOUBsJt8sV20VkvSxEs,iv:UnUAti/Fn2k+N87Yqm36d54jwL6cTKmI8z08HsC5Vig=,tag:pK+n7y1pUN5/sO5pdn65qQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:gKdj3SZM5rMfBQ0Lmwi8VeRTXSwe3tIFXW1z0ypJIAYWLne/1SVKR9qepFS5QyHZ3pm3wxlH0qnq55jf2VYKU5q2BReve5N7DNWkVkW7LHczoFhsHCBWlhe9RppyJcKN9kpqN16S2UQz5US0TJ3p+KuY9x5tVS0HDb/2LVyA2d6JYe8MocQLUjHOi7l89HHEkJag4DgT4d+XD/lSPQlSTOWuyG9DNDmM+tJN9kBvTPUDDZ5zjD5lv3sdtjaODIg8DLUrr9WMLdK/AfZm6A==,iv:AlfHEEaVt9xoae43340mYH+5bakeiVdqcQcV27H9x/s=,tag:Euwfn3gxGlVkoqF4/4ZHmQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:XXxPC9aRtskS4CCMIvr+Ss8vzF+1tkOqN3b4Y0hO/zHXUlwTR9bHMlhFK76PeKFef3uYa+DyYo5Mk6NllOcCwasNCfoKLHr6uD0l/vh3oGuYgpS1LceABo2Bs4O8POyPNG7/kR0yuwn1EyIjz+JW70pwJMH0j+G6lmZsHFM03mMYLFSt6z3v36OfH5JqCNrc3pmbNlVyKuxoCvZ498piWpLzYJtYr584GzLK,iv:+blRURuomIzBrGV6Ou8WWrKqqaHbHjSDz+CLkYiVU3k=,tag:V9YJqMbM/fFpy6RW575bCg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK0RjNGpkdU1pQk5tWEVQ
            emFZUGZnUE8vcE5icmx1N1grT2hjOGg1VmpNCmNUNXNaTWtuVmRJS2FPOW9PQmh3
            QUJOVjltRDJmbXBoTmQ4SDBSeEdXR0EKLS0tIEVWdVlYWG1HRStyU2tIL041Ri9W
            M295YThqYWNlZjZYVjBIYlFYaDhPTncKqS2u5DhzefnFDm4xeA/FvoU+1Zr33zbQ
            zPq6Vtqgk5zDKt26+72bz9vJtKbmtpNGqayeRw2sRGBYhIlYsD/01Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T02:21:11Z"
    mac: ENC[AES256_GCM,data:ec0AMmoPq2SBRXv6n9J0o1N+SuTL2P+Znv8Dj6tSrvCUmkjiasimd2lq7NjSR0aOx47SluDuccrU81puKR5OYnin6GmG903RKvx4IRLSXA/k7RremFDNM3katmsYDDZjxFZYhBI6iAd20nyK5+prIr8JOgTIoxYyoMAVNf3XAhU=,iv:KbyrpWN3i+YaaHcKTbnYW+zxzhAhmRuj6Hpp22Bi6bE=,tag:vLgiCOEigYCAG/8bqKws7Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
