apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5Kt9QI9HbtbPEtsEia94O5H1iFjZAn/7XjvKp9eHwlttDqYyc0+1B9vLDq3NAVoI9YZ5Ze5ePGPRnO3AQIoFqZ2rPbGU1udJzFUtCtObwvltXOZntGx3XDd/qHZSn/M7ExK5WqCl4qnx3k+I1cEulN+oxoDY0Jkcr5e+SkeZ4vIJ1ZMbnaWu9C2fAErUXHOSvaKQl2EtIAFlGzbjkEIvgdssM9D3EOP0cXf2rwXLmnMMIbYeg2gUDxP08ZUSniRQmhp4yxdbkw+O1lUKKgEa3K5Seac1Cucqbd4bOf8kPLFX9MKjK2i4kjVupzK4ANDIVlzUwGeIl6nZl4Byz5GDmBxpRXlYaxguI4EPPGoW56eyqut+4qrXKE+KoSRlLsl8,iv:NVECjELtwkYB9fYhc29Rz6zl4+j9ii1yFK1cs57FuoI=,tag:AY3JJWDpyfp/fjJCPNjy4g==,type:str]
    identity.pub: ENC[AES256_GCM,data:KByjnT3qdyl5VFv87ZQ51NPJBNHsAzLZRSPlCtKur8xyAMl5FVewYx1xqspRmsjEonUjphi+OY+es9EyuHQWbfe276MPz8Q2PIUTRZIMaXwrmT7LNJkn9SCZY7MHUwRxiJ7wGJlckkbpTNfJVYL7vpyPmpLM8WmCrh30n/vd+LeBeAZnj5yySIS497DZ5nargOvdgHsOPF3aydCYhfAlH0FQv5OFep1hyGvEbxLC2s2F8sDiDI+uiILZun59MImU5R9/vqCD2bV2KSoxeg==,iv:oBMlZC1tqcFrXNmVy3EiZ9ZQA/yQKEkTOTcHRy5z8DA=,tag:dQFWmkTYFaODYWYkD+8Z3w==,type:str]
    known_hosts: ENC[AES256_GCM,data:mBso89MGujACtxnVKiipWAoqiEMo62ZZdOuDVLwZfxzvgJbieQeM6TT8udgXmzWp4KWXCr0rY77vH6MhxD+CeQoHa7kHs26CNTRb8vPGGf5z7F91uB+L3zRG+AOqOafQs+9Z/VVSJIbZ3ITCHjHl+0zWYXqSLG2fU70nSm27PBHKJ1fqEy1CCZBIteNUDfQoZHKmjHFiSn5dNvsUmH22tpzDlaU9rVu1sAVl,iv:Uk4/0duJ1l/WZcDsj80kYAhNC1AC8Hsvy7pTNsIvs7A=,tag:xKNZp7rWXSnNjAYiO5QxHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbXYxQkExYTVLN2IwZ2VP
            SVFLeGhJd1JBbTdOM1owTy9adUJXbXc1eXhVCkd2NUNidWpZbS9nSFRRZDRCNWxL
            VzNBTUFqSEwzcmtUMmFLazBCNzA4WWMKLS0tIExxYjRoRjk2c2ExaDdEQW5CSEdO
            ZTZOSUt0MVdybzI3UUcyMmh4WlQwOUkK0CuAj4k0t42IXqBC6bnPj+8GHsfOSSqX
            OvqfSQtGe1+cFyspos1OJnCdYjBrVRiS2kXZ+FL4UfjExx3CZORNyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T21:41:27Z"
    mac: ENC[AES256_GCM,data:HAZNSbCDHioTkLh0ouz3Jsb/F5Zcx9yXiWCmpjZWrbmsanemTnMHOtR9VvOTgyH1XNpav5UfoeCyKKoZLOijZInC/2PDdQJLbdwztSsBrh2tkWuNaUZEZ/C1tVbLW9TDh4/wCPfoXtYX8vKRGK9SBt0qp1gx3tghH/E+r/ShTbQ=,iv:tD7cVrxSz0qeQt04x9A614f5iRlE0/gxroC0lNBecQU=,tag:FBZpsDSgQOzzlzii97UqpQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
