apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lB+fsA4A+Z8+I50lP4zYiXUnkcSLQWjIU46iFalMfMiHjv1ZiGP9llq6IqoPaYlkPp7okZFicevvFZTw+nxbRFIMmz/d90hZh95U3h71/3tL9eI33mIUHkFxEP14NaBJlFl208zUCdbUcwcUVEet7KXLBxZW7kATR6KujfO1HOW/JUy4A1OPgZ87FkVdD8yd8G02bjlumjmWMF1KKFeXhmNgSc05oYzlzH5ZZvZiCgMCHwyp0NxLyjugJd9bxc5DoxX7tYthZkucCsG+AwUswDpqXASITsb8h8Xl0+i4ExHbV37H9n13mbb8EXWxvb/fTTjty052SLjGpGyIcYOfhlqnTCr/leEUKrdlxtt0nMCi/Lx9gXdgaV/j5UfPiGSh,iv:dVAoYcaRdA0iU0kAOol8dM8gO48yC3Q+qdb5se1PZAg=,tag:yzSYloGZUh4UJeRfEA/ZlQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Zg65XuXSA8hfxhJHhP8Dw0vtG8vj4WOB2TPw8NDQ2IjR1qk21ZsTreZZ7cf4tD3hq6DOt3sE1LXSDRL6yqkO7JP8Jb8JQyyvMiGCZctE/uU3CpOqoMti/0Yy9DZn9hVdXIEQ8PgRcoSdXoNwAQ/J79OOoLavQKmzDDY6K843VjY7eApPa/J8GFCTdxMlLYpwK5zUr25CLXRvv/mv+e3JsMTYPwY6GjEc068A1uLvd1YIWcaIlz9KIFc9I3EsazCkHREE/Jw9dvzB1TbCCg==,iv:DsTUh0lDx3dFHcxAiXgGFW2lU22VqBNVG6Ja4YEbnBQ=,tag:tR/SiEDMyIkrkCJ7ag78RA==,type:str]
    known_hosts: ENC[AES256_GCM,data:O++4teKqlhBTnbJQaoE+68Ehb9g1sZM8Ip8eCuU6dV0xphOqoIPcPPUq8fEJA3HpfqKoZd/XWKPhCbfaQXqQ8SEU0Xpck55LTsSPFhJZQ7vIX+nDScso7RNlIVXsSKIlesmwKdw+LYwh7b9ezTlKYg/52dl/d8BOUi6/wDsOMUrPbWEAS4atbijWafwMlaXTCCdEJo/lZzYGo8J+MjygJmktGOwQ8EiUtzBN,iv:OLqBf0jlwRNiqFQFnuKvp6LO3Vgf/Ycqu6BKVZ0om8Q=,tag:JDNp7tu2wjUfkfJn0SU++w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaTBTQ0NWZlhKdnllZENU
            TkFJK1RybzNsNzNVTXdYcXk1TXdaWlNYaG5jCklxVzdRYTd2c3ovTk42SEV2eTEy
            U1llV3ZKUy81eDRCQmVXaUVKTWVVUTgKLS0tIFloWU9CVHd6Mktka3o3T013T2Fh
            azZuRFpFZDJPY0ROZ2RkelFzYUFhbWsK7lXPDpE27eu6fg6enF5g3EManwpOaSTM
            Ok7IYOXcrOfAmndHpFhraZVzrNZkJA4ZLkMaxVA+EeXIZ3SBboy7VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T14:12:43Z"
    mac: ENC[AES256_GCM,data:FzZ8++9Jt8sXHg3uaFwRuXAh+ygWCeJTeMjJTQD0C7gT8jJIa6c0//wPy/IUApfb85zVG5BTS1gynAQGm0/l7c/GtzHwW+uEN0JYN/Qpv/H62ce9dBje6swsan5QNFDFBU+beexZERVeHD0tMlH9RX4RBFKfQHBy9q5anqXp/XI=,iv:RxFNgciXTtFODhxkF/NbcfWfOlgzicwHFp8kjfXBfb0=,tag:qArCIhhGRxhc6qCz0PSWrg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
