apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:W0g7wRPsGhRDp7unA1rWUOATdvseO6q69KSK0BuvDwHbShvqF+X9JRRCEsnypwGlyNG/nFt+ppAdTeYeJII49MOyM7wLpm+oFq0kwXWuJmbHjQK20N7CRgOHF7M2LWaUwP40CIGoC0PWyBVS0uxXHQ3BUvoqaFYoY1VBbI0N2r9I9cYmLpgI60VlJJJlgltf1sPidQp2YHCDIICGa6zjuj6rEzQ71ivBvNUSzFDiZ6WiKVtkEd6ksV+zYNqRq4GbR2M0Dsfp2ds+FeDUk4fmQ9WVGZKf0H0nRh2JApn6DEsIkDW9WCz6E+EoSmBH8nxfwI0nJtZLfyfQiEVz59zpyOwr9kfyDUyIq6fSSngmgz2C2T4cumevnVA7rvNaJKoV,iv:YSnkhFAGoLIoorjx6qA9wsB3wSznjdlo0ynAWtPlDsw=,tag:18K2ZWngvUohizzopGyv+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:FECdCyocg3bF1yalLHBvglBAAOiMuj7QB5RKuKeKmsvUNKQZgyAa4i27Cz71jpKsR6ZJ7cQMcCo0BlZLgcwOsJIpLfCJ9j8RcsbSr0gbBquDuUzt7vKdkzgdlN8wNG81svY5aBzFo00m7pTAmsAOIQuNKF8qG88vOvm/2wMtQl0aL37jUHwq1zt6zIm7qyPnu4Ui82S2v/R/n4upiotrSAs4meY4sXD3xCog3Id2g/sBeKadpTlrhcO1lzrgVgSdnz3YV7adUGbzdlWyIw==,iv:1eNcqL1D8S6/ZPwPwoAoHFpa+8V1I7q4HGFLxeIiGBw=,tag:cxCOAtgzbqVH1nyoBFD34w==,type:str]
    known_hosts: ENC[AES256_GCM,data:i/JUTFSvzC7IzyU69aAzHe9fEM0P/PijI1swZN/GBYc5/6mFQ0cQA0cd5Kr5PUJhvquSzrce6CqN8ZvxjjGLAnP72gqX2p1VV3hV00bTBcyi4Wza9aiyNjJP3oiZUrxCeajCvzIn5mmadq+bCkmrBFKdr5s02W6ZyGTCPequ9hS/ZpyjP+KFta398dLTuoFgGjz7/KJXWRZnhQNPWEmOOM/oxoR+BD9zSdMa,iv:QnfmFCXrGcSX3b3PzqHjUheWJ+ysVCwTW5w1zuqylBE=,tag:WmjdFdWOH9WaITHWOb7DdQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y2NpenY3TC9UUTgvU2Yz
            UmlRWUt2NGl2MHdwR3pBYXdzc2ZRTHZlSEVrCnIrQTlQcWdOUElZdmh1eGl5UE9N
            SG9IcVB6dTA3OTV2QjZkWldmNGF3YncKLS0tIFd0dUV1b21Jb0hBTVAzVG1rcE5Y
            OXdwR2puanN4OWw2cUc2QVVaTFNLK28KmNM5aTThApukgC8u1aFPjWyKfNSo94u8
            XtKpJmywwDRJQgKn87tH5/GFRWqa3sbEs0WOP14LGjHshTRTS9uksw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T12:45:42Z"
    mac: ENC[AES256_GCM,data:XOM+cyYfUK6QFsCv2uChAjVh3VdmQ8F2WBQRWEJ6+BVuTQrludxF0qf++bL4OK4w8IyZ5E6/ExWjN40XmPgBn4GzecoK0mUqQruJ0jHKd16DQpplM7V9y2jZwtAT8uB1LtKmUrCI8QHvX6m0QcH5VyZMBXa3V3UDFs6gPeWTnc4=,iv:DT/zUC+aiLyv6yqwfOKs8yl7SrcFa0qVHMABAZkMWZs=,tag:p5owb9bIrUlQSKGnvjrQyA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
