apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9RlZ2P505vR9/U16CcDW/cl8XT+RFlOuvWbprKcvq555+AOa5V+4DIEujNe2HX/PSssJYir7Bx8HGGKGjJaxjLcIVfrceloVFLEI8lU6kPyA7QMDFXYhekqe/vcSWkZqOVgDsfViGd/IUjEE23ye7vVjlC11aKj9IVXbHHQVLHjVvmQdzayrDZSyIggN8qh5T+QYEr1HZNdiRDj1YhaHqq8jOy3Za3lnAaECmP/EXMG4Z8xn+LCEdVC8dBC1F0OT0VVSdRt1zvF+YUjmYw6dbHcakGMBJAqUs2H+y/dGsK1xkF+HPWxE/Zxyc3TcoNKbf8iWmqrzgkNblj5EX1DVO/DL1YrRRhsIFyPmfmbSbayOCoglFKikg5RUell1StcX,iv:WUVAlbH2LLeG/BL+N4CEYGrvr0V0BuQ6HvU4WziOouE=,tag:sETFFseniyAUpqzfRgVmEg==,type:str]
    identity.pub: ENC[AES256_GCM,data:TLY/uM1qtuWLc6G3rZNCETbKIVIuHigm4a6nFddoHzuWjaXEP4GYSEeqvu/NsLtZ0HK+Nep1fRttqeaM5xcyVfq/D5zHbx1k20E8pHtwYDy7Tc5jKm6EcD4Uu+QYiORld3hVe0DT2f23KaqXWhgeqCTy571rdiEK0aVgzUbmmsP/57G3St0nKZ8bJZ9pw+SGy438d6Ri1slzf6WGFsDBZ/u9cOsaSz0q1znVxaJ/uq6NC86c3a9eGHN9MqLctLCzlhknn5Rd2dkLQ4LbrA==,iv:eNpeHPEA6RzfA4bVAIY62AguNhEf+GoJDx1fcAC+n48=,tag:mkcGdROp4fl3uwIOf+EEbw==,type:str]
    known_hosts: ENC[AES256_GCM,data:LK1TkzURVqWGPMNqSQ0+Dui+M40Cf3bkkmI2RIumBa4b+Dq7Pt52d/eFwuEvE3QK47lMeZepKgBiSR0kU6UXyk/YUuzd5QSuk9Z4bn05EUckwPO21D8QAyuqx6Kp9PjJwgf+V2ngHHXvrBYO15JDF0tDhyBpygFopcJLQiVA1bNvbLufw+6Jr0Lm0Tpm+KmFQon/x0azvSpwSv2kfw6DY3zXUwKYYznjpZXm,iv:OESVNMxBMtdew7SLgBL3RYgo/FUUf+gA1TCWXZO+AjI=,tag:Cuv6L7YKi+jx2FoA3kid5Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTm1wSVRnbDN4NXBGVU1I
            cUxiYXQvNUE4d1paZHo2OTdMR3hqNDZXVXdnCmhSOXNsQ2NsRjJXeGlMM2NBZUQv
            bk8wN0JOMmFOTFk0Vmx4YkJ3bkZqR0EKLS0tIDFVZng5dlVEOTMzV05Md3VsQnlY
            L1B2NmQrVDFiVXBOT1ZMSkQvUzExMG8KyltZCm+19f7/cnBYGesjCSwPLc0Znroo
            ChqqknHPAYMRawyeNs2iTrjGFdVA5JOw1G7U35rHNHybD1zGk7qo5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T14:22:39Z"
    mac: ENC[AES256_GCM,data:bvqk5bsZYXHzG3ycVpxpr2EvhMs35eDBDo2+hdfA0zDG7VJ51iceWxWt0e434XobMTrKilqdLoArnMz+NzGdiblVodgmpJKuDv8/u6Ti72NKSMlYF2jZ/n42CX37aibEB89akv8ZgB0+ix/3b3dHN/9ngW9MrHic2W4VnYlINeA=,iv:CZv67NByDqevyiiZSvs94c02QBj/W2bc1TiHmFgFvdo=,tag:i26Te2jFwM0X69hQdg/ELA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
