apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wPCRxdc4CFiGnw9CAn4duBEMpae5IvQ/ftJqnVVvr93Zaa6Qo3EAL/Ap4IZsFGjnQJ1vQhp5p5eJivzFB5qNcymzFw1tt2RnRd9etEY6e7dfG6OrNfWi28V8tSA4GKhVuIhIpSgQllnl1LNmLU8hVl7P0kEbBwQ4o89y6y1Z5NpJyj4/wfdQCL5IBpe+IqkVADn5ybfHRr+mKYxxAuAyA2OZT7nsKmP+8lq5OCY7mMxWkDkUfEVxzypoUJ4hszyDCJoGSJvgq7B+pqGATRO5GdwN8K0a9nmmjAm9XcZ2Std/gFfLCaXxGvrsf9iG2yA+kp3bmpRcnrk9gnKQTNddIN5K67JfaVHVO8GS84Mxf+le+JOov/cSfXvqGon0hXuN,iv:V1n1Y4EmxJ++0ueqduSZxZfqXWcSrkGWhO22Lel0oL4=,tag:8u3fKAFyyPfmqYPY/axbdQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:4OWWKCSPwrMZjz2vvj+nUrGCjp112RyLLYRIpDeU0mqKJY59BG2APUucD22fh/F91dkXiK5rkclG2/bWFt4M6P3Jv9Eb2lMhblTQcww+NpZEG+rSJvLB/2Xaqu419+jjA3rMJXzC5DCc1JwC3IE9qQSBur5LXQcLp0mx1RIZxjrQ7RkZ9BWLoyKf0c7CXJzXXiA2ZJ9QfEgzB05mDv58nnge8amlwx0A1JO3Kbcf9DdhoEi26O0c1huZMaKAEhwmpQRCmN1iK91rBsSAMQ==,iv:FeUmJNJQLRHg1PsjTgHcgdCEv8gJ08Pw3/DCA2S8QII=,tag:srL6SPGGh2YLCgK3S+quaA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ANIuTTTSDyvmVZ8AYvZEKEA1UKstmdaTV7mAr+GVeaO9Is3g3o+3awIG1qYNrmoc3A2a+faZoDVJGpiqGwLKtQTSvThVK4mN14mKYnjRwLoSHt6vyxfhJX87Gjno8Yqe1TTn+ViUv1iQXfLCi9nQw04VstCMufY6zEYI7fDNmpfrsKkTC+TEpwAH1kjzsLYS0dzmtAgruSgFSqSDQ+U7pgI6s6sthP1cbpFa,iv:2u1eaxsRJm7NRVnf0eoLIcTI/6KKDzgEI/8BymEHqck=,tag:oe7jXsxmxnbV3iOoi/zcJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMzUrckw2ZkFRNVZLQjRy
            UjBsQzl6dXh1MUhENzFycDM3Ly9zRUtZVFdZClZNNlhScGNlb1dMU0tVcmZMb3Ux
            WHI2TS8rK3hhcTJWMFVKRUFPdkdoRDgKLS0tIGU5RklGZzdOUkdYNjl2OHl4eW1T
            d2ZLVDJNck1DOUlucGhOUGJYM1puZkkKc/YHAACjveYRUFPrQa719NNSyE1tCL9B
            QLMbr6m5KiA3KYJ1J3vsMoMozyiwikRfzuJwY9vAgFWXgL9XjKElQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T16:55:47Z"
    mac: ENC[AES256_GCM,data:gPYLAV3sfmdfTbdBgLCltN8p8EoDBTu2A4MIvAhjWQyDegRNfMcYamirTW7x73gXNdgAORJU+fb293qFzebhw4/GTBazzJawO+bYWGm8LXqcsVvY3y/rsiqHyiP5tG38nrhCtfhvXJMqDGBUP3YFfBd7YlncvVvoFiX8FUGh9VU=,iv:t9TBlyr/F+YgOiDbpT4OfrW46ox0MMcyP98eSKbnJXU=,tag:+wDhftBwsb/lSTCFRZBzSQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
