apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+ucY9VpwfCtZsanpStIUgOMkaHNNOYUk0FO0IRZ7hFimiCkFFfOtnnt6WgYHbuLBeHekbp0jeYIFgKfgS2GUGoq35k9tZBHzWh8XnAixezfSFWT1zGlSfavzk065qfigPcIu+eflCOTUN0XSWmHJkD+klEh+onXNy0pLgt3rQu/vewx7Lij+K4uEtg47vxr62RkKt65aIEf4t/X/a1/TKzkxC1SPOwse+tchcx0ALw0KrRkQmudNoPpOX9D8BoF6eDCS4hzAqoxHasPon8pjvkZjbnwhby+X30jNGbFezCxSu925nfxeq3prLCatZtX5HawQ78Y3NQl/FH/dlDIcShuLoqMMkzo5+se6QzhoYGKsEa5R4BESj9gQx1UzBwLX,iv:muos4jqPKzkJ8lP4QXaRMy9PEVMhywZKasjblJL75S8=,tag:eB8jSLmVS7JOcQN5PSyYUA==,type:str]
    identity.pub: ENC[AES256_GCM,data:V1xuxbt/D4zsN9wjC9Io6D1m6PVxlfeVqSzZQNhZORn0ZuNISzFhHXBGqyDx+4Bf/7Q1YJtCeYrhjtFZwFBAqgO2nztmKenK56yC4DuCc9m47HeH3+bW0dSXOdzw1OEzgxl04oqkK+uXan3IvCmusylwCXHYk3QAhoYqhHokjrHljHM5pV+7xXNiMdOFdZVNyTQOJewSd9x7suUIEjkP+HxI2v2GZTctVf6bxEXBeCi6wSuNlAxCbHEWBsf/WaPdGeiSbT2aT8K5F87Hng==,iv:/ZnR2kqrfBLGDmtYAoNNjTk+7QxjYSU4vQ6WDK2A8us=,tag:btCnmGeP6CfKXyiWvLqE8g==,type:str]
    known_hosts: ENC[AES256_GCM,data:IUs51x0M0L+NgySuuqrBgOjeRtNZaQpZ7brhxdqX5qy8v8340rTqFnUafzP4GFlzWUJ3HVvu+yBtz8ilLPEGU9Fx11L5gUqMrIC3FmrG1WQ/GhvWGIJHcIIXND2R35uBbb2PnerumiEiCK0bIDSkEfrA/Vw2jx/dKmzzhHBOt9IIMQIip3yxPyTOzUXRjXtGg3Id3mFeo+Wa/U4zI+3c4PTxl0yKL/YnySkS,iv:lfmSXNAnc7xoNf1FKrvu8tTzCdrlRjVGOC86KRNPB58=,tag:ZMxXUPhmeh+PbPRckdlHGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcHB3NE9pckJiS2w5dDh1
            SFdaTExnd0hHdGNJdUx3blpIMWl4Rmx2dUM0Cm5mMCtHUWVML2NIM3YzT0poV3Ro
            ZFpKOGhySWR3eFYwSXV3NnpMTmE4QlUKLS0tIFlRU1hUekJORDE0TlJUbFlGaEcw
            Rmc2dVpZOWh4a2hEMVFja2J3WnNGbk0KjD3We+sn7e4aDpEyX+/zujGVJUDnqCUJ
            H1JRBmlGj/Xkh+LL3wmOjToAgDLH8AEwnxgHd4qd1ju0YQ6FeBgs8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T20:29:51Z"
    mac: ENC[AES256_GCM,data:loU31EWoIrNkgy4XmwRiVZ2BVsrx78uX4ygM+6+zCB0WdzmRsGINwuzxLsgJs/On2v9AG3bxALyCy72JydVsSZPGZdYreycuom+EPaoiCq8eJcj+LcYu1ivGDv/2U3jktWUxVA6WfJpAAx0vkx47rhX7K82XDdiuoWOwuTQ4Blc=,iv:+FmrEBzm+PrG866d6si16zNS+mfMruR2ls4chAAh2sU=,tag:DfgLjhp/TnwmVPT/XhiHhQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
