apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:w/8P/XXGJk64e1bBd7Er9wmipO7V+wBSACNtfAw0eBoUx184310zkcuFBPa09SkZwh+YmFnuAv9iY3Fd0dq0UM690noK4lbgU5BKbCKx9sTQMBd+CyaktRhFtF+66JtFY0ODxl2lF7AZVhUxXdXn7QDLsJKqxBGgTUOSk4aVM9pRcTycvzOvw8WrouLmn5Mg+hcjBDrTa0xHEXaOOvrfWhbKDZSdiTYdTj5OuBwAafboQwW5wb9ghyMOFmMc74XxPlAFQ+BnMVHYX/yWTiVUTEi53RtDhbR8SADo5cbgRSVqF+9riygE8kc9j8Tob9e82rGIevABz4ElsJpTzZXAtDDM10q0OmkaQuju9JS2Pw/nYdTZzoGnFCN+ccGno2AO,iv:EH7x53nv9rWsVGsE0SFkBZyHnaN6NVvTjzfGI16mxro=,tag:QAzr3SMA3PvPJLWacEdVAA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NPdeCrR6f4Zpiu+6PU3kwbUymZgkQXIbskrLe3OKITl5NJ6ybycQNKChomD7Sz+GNS8G7yTeVqq1oIqVHgryQIxfkeQTZP+G2QiwSM5g6SWElalpuhVxtyDGmpQZcda2dmJ5fzr80kk3aomv8Lmig8MnaDTQfH4YMtMaVHIRt6/GKooq+Rp1YSS3bqeiwGUA4PZeXp4QKugdArMnW4dXwRqIXrF5IfOy/RRFP0iDz/6ZEitFKnmt84OcoZpzi8FUGuluZZsf17o1vmnfWA==,iv:kJ1JZyVA5LtR6SUOG+WDXaa1NOPTxttHFQWQwW/gako=,tag:2U7zFGEWOFSBlYR5Or2JYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Aw5XL7067L+l5IbrbgcWNhVTdUpm9O6bbU/3GKdlF57SuWI9Sn3yuhDEuVWzx9o4hj6jFeVlam/C7wPWqPOYA3zdOkfJvaZESqDC0KPsxFDBCmH48ne07A77qRIXmqZRYlrHbTIM+VJ3kxgN2UoE2tLsGHfTK+cSX3XF6cbNuOLh4tVLQabp7uP4Fs9n+mKt4uiD68Gif0fDChjyx2I1hUUj/r2sqbPcRzvb,iv:XfhTORgHAxHPSacsyyUI172G20ZKCDbJinDjM4qhu9s=,tag:LOFfMefsT9fqHSR5JGNEjg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTXNMdC9aeDV4VjE3elZo
            RGxmWEtPOVlnQkdNQkhRV0Z6azI5UUEycGk0CllmREZhYXBibDloeU9oKzdYbkY0
            Y3kxd2djSEFMb1VySjFCWjRXNmdKZmMKLS0tIGpJVXd5bkJmNVJKTjNkbjNHUVZK
            dVpCK1MrMG5nMFZ6MTN1NzhQOHhEZmcK/gfWGgo0WF+s8hjbSx/H061STs/hqYEu
            4FLbU6g59Sz+UWLmFqKO+yq/mxWk0Pbc/cP+HbDLtbVQ5XD/CJAGvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T12:06:45Z"
    mac: ENC[AES256_GCM,data:AOO0P++PSQijJBGkYYfU1AXaoertkri14POHApnZKkLvaYUFimVz6mMK7gl5dlzzKHqkKhDZZ/jAmC1Iecx3gndBA3jm0ZD9AhOWlWhNtcL2e2BNu58TV+uavk0NrBuuCNN47cS+FAaS5+HRJ6doLsTC1ZsHxjBWkabYGNgWz38=,iv:RIALiIvL5YmPmiynGtNwIU6WR4WU5se03npWdc6RbbA=,tag:ENmOQsI1L5Z2YzSvlspdeg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
