apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hIK6L3iZmBTvaLug6ikG2DuqF4vud0gOS3dosNGKAUyeIlAZ66Axvdu8Jjc9jLRXiJgDH77BAmY3/OoQAGWwktc9zD1mQryAWepi5sIujzgu6ILMui9ELkCUzDwtSkjFUHnXtlGJVDo82XPTKUN+nesn7ViTa/22efGTuArt/DKIzP3ZdDfVJk7qn3avzyvekMwdeUbDCFgjW6Eur414hlUA79iuzX+xs/FUpOeyQgxVrvFxdQGN85tcTgpiNr0bYs6ZOWmud7ehH6eFueClC9gU+oy8M2O9q0wiTSJ/AeZtAmbG31omqK0TNmRToH1YOuFHJLfFxisV2mPCiosvzG0b7BR1k2THLAbReiOqjpYNw6n7gLxY9Hkl9R0g6FzQ,iv:5DP9PPhrTFGV2UwLpdMJxwCmTHEz42nslcxM1jzxPJE=,tag:xZF0knP50cWcKWyJRqHtYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:NpLIOGfKDQny7tv3ujIK9FuB/g2wRXk18imerDatPE/AIFLniR2rNk+D2u3yUl/PMZ8/1R/DXL9WnckIm37iDPHbKw8E4lvkkNjyiLJg5KBLihFqkgKNYd08zhDT4RhwaInY7AK1Owo5iy1ofe+j5lSXTgsG73ao7BQkwK/GfPff5Fr+YrlZqHS0aBaiYZAmZTeI3grgc4wG6uzUcJpugv0AIsqGm9orRSYBJC5AM11e3kSHhFnRaAFr8Nrj5HcQfAmW3GDtpeEbMUquqw==,iv:GrOKpskfCHk2SQnIDbppEPViJePs/L+Pf2LY/gQ61vI=,tag:czyndihL2RUNZ+7w3sj9HA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Eq1/23SvqimTmduQdluzh+fJpAfJWCuJUNmGISE/ZYv4ZKCYMp8gXep+g/afsqBxI6nKXPyrzyiGCEkc/t++1ym4PVrKiDf4LBTJMpojC/7JovoseEYiVPV5QwuX/I0MzfDxuI7AMNsnq0Gm259kPZQ1onA9j1G2bwAiLpZbhv9dR42dWCb2D9xR3JV8HJRR1DLsXb3JumDWrkXV3u8gG3f3wzVguFcgby8b,iv:CF7subCPXGGIDG5qkg6YQa72NO02hKspcdoDeiaLCUQ=,tag:eY5xDSIlOB9PBcgh4o2R7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUkdvVmdzaEhML3A0Tk54
            S0pVRnNpZFJEM00rS2gydU1UcE1KSEdaRUNJCmQ0aWx2U01JZGRydWk4VEkxWngy
            TGRJalhkREpGdDhFOWVIM2VlOUZZS00KLS0tIDdRU2w2dk9TVTJhT3h4U2xwVE9p
            UXdkeGVuMWdVMEltVXpudzN2c3M2bzAKcFCcCGfb4b56q/I0oEBk1uzc/WDaYc3R
            TWlxdUlCdkC427R5BOah2t7MsQllWqDjnpasDhzIIFVh6uurK7tR0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T07:39:52Z"
    mac: ENC[AES256_GCM,data:BdEAtqkuqPzQq55TPD961ifVD+mLJTBWPKOEox+z+Y/wgZGKBuUkkVIWRbAQInQ3docpe2sRmClmEtF3j3f7Yfm9ucpOZm6+ydg9X+XIULly/sF53Nd0U+qN2zRxSeuWNauFTiyKGFlqFpvkktjd16GxxOHIgqzGjgQrYPfb+iQ=,iv:kTDHTER+VQKy3GQAiCQoJHT8e2K3kC8r9e4vQ4/+DQY=,tag:7U6Z7TeT39VH4KVT3/1Vvg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
