apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:t7J8pX9RR5DkLYr2Dj8+5HjDVgFMMdczk0IPxeu89hkRZU7RIPZuf+mmhs4RmnIdwi/1acDAZpFWQk2kj7hJUniml0io4idNbfoTO0kPskloDsvKeIJFQw0Qpi1IiTj9VNClO3+dnOpF4nMzBNG/HsRcsGVD2jphxphoF4aW3oKPozIRuAkX7TtqLCFrvQ7fHAwT1xiwLjEUdkzDfL767YcbPOk6uooKwTmMu4ZA81ln5JkREYueZn+LlKXf++KToHVbGEGfYO85Xqz3GE7dufOMPR7yfIuTgDA6TtrNza03ootfJWCpIpxIpD6ex0o9a3TfQtxOPh0HlH6q48js1gaMZK13/SQTJgFvS2fcNktDKeenWjlbsvxQfLXDnWZk,iv:lNgrE2LbtrK1wSwhY9YN6AsgRdgcwMfd/VkIDaluPSs=,tag:4V5nNLc5J4FOdBROxvXtFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Cykundeeskf1yQcM0sJsF2ql3zyzj/wIED9R2290Utz3uprFQZSJi23BiF62zaZGBQWI2W3AVUfvmqpJMCXgWIouY0oYirRFuL1MHNn9YZYZ1CO4FJ0MCeQMD3cYPTPazunvS5NIwgOZ8C9jjpntKxy+KeKrjuJQS09A7k3q88Fl5yErcZ2Galtx6SWMF/lRmRF11vAbDgIIgEMIHy5MRenBTAkvVXkePrr1TWPYLLdUCFWt9lXbnV+/g7Eb/zHlabcIYsLaljxcDcB4uA==,iv:9PaGc2BN3xEmySNUg5cvU/MkHjRrpwl+r5+fEJAZoE8=,tag:L2XNnfyge1tGVPG+eR8S1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:+b0lqCsegq1cqdSNeqbmOqEmavbCdvAtmvZkS5DQXGukOlJM2UTJsK2HzHAWEnslvZP6lUiT9NKwcQCBpHlVa9MkTPpoekTfsOj5Xpyq/R/nLeN1zNfjTyL3Y+i8wRYJUhaxnh1rymPEFhmWGCGLH2TSphFRdRLLhoXb3xVxIQ9pct15MppwJbeB5OgbDKw2YG7BNkC1kPnwC7xcQoHQz6CB7ZJO0u8ykznQ,iv:QO5AfFHOrOc/N2uB0l3tK8NAu+cIStQ9hv76kRFsQVU=,tag:wpg+KkjddvSYlUCWYPRD6Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbTBsUkFnYW8rak1tRzRv
            OWoyVUpxcFArcExjQkpTbmJSRHpFNS9VSEVJCm9sK2JrS05CbndSU3RaOFgvK3Ry
            SlZ2SWNpWWNtTFRvYVJlbWdicnJyQjQKLS0tIFJHYzVmck56RzUrUU9zSWxUWkVq
            SGk5RmhZdWRtYkUzZlBQdzhyU3NNTTgKzdNEkSkl6R8c/whCbMAaw2igUJxLepi9
            L210MQ0/mtxhWMgevEbqcGQEXd0Qyrsn4DvMeg+65AUFX3KhrhgpOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T09:13:57Z"
    mac: ENC[AES256_GCM,data:jzcon77aQwvTnRpfjoKbWuRJBgG5sYOrages7zfQaNa7SFEgUcNjI/NaHMBWtmzJeuaB46xptF/r46DnODQs2kAtBcOhqE+LN/MufQb4ByAa8WKq4tMRFkh1sVp+HwSFHgiM4l75lcZ+UYDKftbDaeLF62TAMat0L0vDcAitm7E=,iv:/ZtfM9eB7GR+rRxcf1m/GCFc2kZ1q89vuEfFZbnnAQo=,tag:WxmqK6m3kQVZ6eRrx0XU3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
