apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XJqo+2A5p27z+Vk0fW1V5Q+2RD3Yg7wc32JzqfiGxoCp77lDfmu9BQkbcHTnzMTiA7plAY90vw8NX7CCCpAvSE/oJf4tBBIcCjn7gJAgY8wrW4qaxO5DwDDoN44B7v+YWJKilEclJuCYHY56LtCrJ5ulkYF/plwU6WM6RLTfSt9GFn5JuROvV28EvzqidoSGWLQ1+uVqWTkqicj2rEoJ344oTezFVGcSjL8Yo4ontitfrGMnbBKP39EUnN0ITITIxemw5aOLvKhVE/DAL034rrQg2I7/wAGPJvCbdKcD/nkYcXmkFw3xeEd65aoA21WiFaMDSktTqZKv15qnOfDhqfyiyJk75rYUp9wyQAxUJ0sB++hgks1SLZXh//P8QlU3,iv:cwqGgGPvH1dr4wpCUH+70jh5mpQIPwc+to4BchhPEEo=,tag:s9aggkDKHPi53j4fBvCPUw==,type:str]
    identity.pub: ENC[AES256_GCM,data:69g90cPegOu/BYYOalKbvr7npZwm8AgXxDqgsgy7+RSBDwkZuabpeerjUOKZzXnMD8U3iO1jzikmKh5WoZ1VvxLdfLX3Ee2INuFV75XevVVLOP80HdhkKjYK2sQRxCTCn0QLtRX+SiwSPACe5zQwbzgplJsrLD5iRXdC1XhoSf/CuMP2Y45bqDA95PfHaCOxSZflbUvL8yDjqIunY/0jPnoa1JflcGab9gIenDxUf87yxHmlYc2+P4h1QDD28DQpk3cdBnFvSZAx8DGNuQ==,iv:XN9gjJHiBwE3r3qFjReB5ry8Q+cGXMnx94RIM8c7bGA=,tag:h06TssE1WXdfnZmbGgQhcQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y4f0evHY0DYL3Y7RABEMSmyUbu/yUfyDj1xXmnsI3NV3Xlp8XzD2ODJto4ZtuhOR4Hh+0onuLZ0tQdw4+cAGbwl7f4dXAAne7XhoK8qw1Y6LOZdIx8hEtkXqywRszJo++clJCUMuwtYvEcmAoMcuV4x4I6KSAzBatPKl2L82QWxy9rtCB+PggrrTSbqjUl0EhJF5lgdFzvdy3Mzmn0zzMMT9LeB/DkMcQssH,iv:7wQ/7Mgl6Ob0ZxhHKAQ28uqRTbciAFm1d5kF2ug1/Lk=,tag:xFUmko3ulhJZ6AUhJvrAug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWk1CbGxYWi9oVHJlcTl0
            ZStlUC93V2gzZUtFWUtUWFZqazc2MVFYZmowCmE3NFZFY3QybE5SMmlkaSsxbzQy
            UytneGZJcmJoZWw3Q05yQlNqVTN6SDQKLS0tIE9wN2RWN0c5NklFdlJpTkJ2bVhx
            QzZBaTFsQmxWUzhXVFpKdGZINFh2ZHMK6K0ZHRUIc2r0fUaQhmIik6bJZvTOULli
            tuRdoNvtP6Hq447/OgNq89n20bSqltGDOqbdtevkLs25vLXbNgRmVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T16:39:35Z"
    mac: ENC[AES256_GCM,data:NjB3mLtEBlaz+gU7hF1iovAotyRFcM520Hq39/hkbY2Y7hbT8gyXHrsoCLQREI7/VSkDrSs8Crfgt+J8KY9IR3lijsrR0+WPFDDMFYT6V53B0O5Y3fW2AkpVc0Qq0BDpJkvnShU4QPjN9uykAsNcSPfCSsUtkKSWgNq9Z0lGhUc=,iv:ntG49lz6pX0lpWzi69Hx9rJkILbFfFwvo1pfi8ADOXk=,tag:R0ze5XTeMH/x74g6ngy4bw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
