apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+I9LAGUlmr/rAMttWogxu96X3/oSn1ry+Y+v4rLgYxDb5T8gB9CUzMTkcDUVtT9DRzc1f4RKB5YwHpLImIfgppC79+Fz+iocnYiVquZSPNT0HFCxwWV5RGGGGJChETP51qQPQ3JtHJeY2aGPMtf9VmgMO5TyJ3/eKpGkb3iVufOpBDpxWzStJiYMLjDFXayFVz+uZNOZij2D+qoYmIHcxj+4VUwFIltBjMH1HpKaANaotTsfV+Qvqpyvp2ggApQV6NWYTDEGicHyyhQFlOMSgmfx+6jC1pA2eIxHT5HUkDw0i8XDZuk2FOLceA733FbrcgemBwfCD2F38deoCx9Y7ENZRLR1V3hFoS/D3pVk3Fr3zxot4lrjO5zl5EQ9GlIm,iv:VIPUibaElRFa/5f1yeHA3zfMhW8yP1Qvfv0g/NrJS6g=,tag:kfesSv5sucZJ09USC0HqOw==,type:str]
    identity.pub: ENC[AES256_GCM,data:pcD1ZKK1uLGJoSE22IBViyuh+FwRS7GuG31p8PegsrN1semAwz4Sj+JZsrTCnISW8xHETjBDIR4gNivJzAATQsAukUYM9phMOJXwFSkLtFX8cmyVNTCYN7EIZPcMk0nM07df1HTmpoIiXrXiv+C5KCtr+gb5pqvB+riSozcrAeFMiDfj9jq0MJMPEn3VVvXk0HNjnonjY4dc2791wrf/zxUmg5Jf2D93tBfSFMTl2b/wshmuM6AlOEg/WoolrZomqibv/4VsnLaBMQv+Ig==,iv:gCWY4l5o79y8wFbxsgW1gTfj/+JD73Rdol9w7O2nms0=,tag:6U4bTNnuyhG31yKix0a3UQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:XD3xpyV3T69xebwrqnFx0LeA6Yg9SVlHFRoIkhH0vYBzK/MyoGKKCYvLUp48wHiIRIlMU6NDitl39ZwYyPm2UJITNlhsF7PrtXBZRF26bcLw6i4xw+ghLVO59yIAQcUqWpuaG+bckEx6MhhSiivg19wmOWYheEOadrb2o78Wugx5NXeRtIzk3z/S9mRadDRynTdyAYNDMsqn/whM6lwf3KJOHy2B0ymYcg8K,iv:BBRQ0uKPPhMSyg41SBtUoo8/nHlISLJ96iaTAdFlzU4=,tag:WGgEvZ7MZ8X5iiX1URSJiA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWXVVSFVlZEF2S29TWEZI
            QTNaZnVmeGt4MjdzYmJ5Z2o1Yy9GVGxVMkVrCnc3WkY5bTRFa3Y2b2YvVi92U3Qx
            WjJLWkQzNWlKVXZhNkRkNzJBZmZlVjgKLS0tIE04NlRweUxSWHV4cjhvSThuck5K
            SStDWEdLKzZIdjZ2cUd4ODFqczV0elkKf6gzmkHvUQ3wgF8RZY5DpD4l72Ow9ngD
            LbkivxhWwzqaYiZ8hNJWfRoiHJg8pvVP2JsLzgFLsi9yf1nxsc7SEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T19:06:31Z"
    mac: ENC[AES256_GCM,data:1qhP5Qt8ZJZ1DdnZC16nj3A142fvndf1rf2JqkorGZOmGwtRtkficZtEjlXvNcPFc4fIJLTKSkNiJ6stHh1jPbg1P+5MTgbId473sbRBA5J4G8zM3RKXr3zwnyQ0rJZvtALL4D+QJvnyoO38Fr3axL+J3/j6pgXThhubZkeMOOc=,iv:nqm+O0BY52WVBRKbJCZBriTT19Ap1NLp2b+oWhOvC7w=,tag:IuAOFpXG6RQpZjyBo8586w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
