apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7a1LiKrnP5ySi2FEjg2BKJ5lBKzOpRdoAwEEOPYIYAbKFrMC+sLS/mBZnlABdiCOtNcFqbxgh6y8b3M/qgPQr13Kc5GVB4kCuEZSKSpPCAz8KyNQTvXLc2DpRwSVJfYQhFRD0pJkAfzWh0rpikf1R4Q8Fof3/rVJUucWEqRFcpIX/M5whyZgLANY8DUwOopYBdxIpgSPA43JJH3NNs+kn6YvC3rk5dxz6rYmcFgcPcyqa09CVoo2Nh7SxDwv98XN5eL0TPwgf0c40RAVeSuPGXXzo0DYhSVTJ+wdw+bTWCQdaw/AXnfdGcc3we72NFjxDf7C0PN2Hg37+y4xrIwCUAdIlhgGtNj73y28MSDOYcT5F6EpK6ZOouTA1h/8P0Xa,iv:yXyyYxaFcNxmWBj7fBc0Dj39LJs69jNw6B7NoCcwQZA=,tag:hjvKsniRQYHPn/YUPPETxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:maUUFufwoqb3Q5+a1LH9IjHzq3FZ6MfxRbm+PhpIY2F9nncPtxzj/ZEAbhF6evRUsoPj72aFvV8ngNI1shI9cEoiLIqqxcn3ILF6NSJ8n8NiSLnrJgLlATZ1JAPBWp1Hm9NI9SHvup74PmDbaHNzQIhBipXuzi6NCPBCgNjkcjiWlK7pRFfc1nY5z7tRc85h/80BwFt/GgLeyqr5cZ/k3lXrnv36vVUToUlNltoo6icWfkVmRkHm8INrWbQcoJ+G3kH2tHgQ57Amb1QD9w==,iv:bpWOnPXDRIGsSk6EKDW/aJEaUKZAfPtdUjLZ6EX0UEM=,tag:ywjxjQ2yS38n2bKvPvDbnQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:HrrELXmuY+UySFuMPhbuzrd1dnDMATSCprNtR4NpuS+G7wjcVaocNOiIrDc2yyLG9AsNWc4yfn1TDl1F36vAq4TcmMonltZAD8daSJOQ2PlKx2zn/zj7bmQpNrJtYNU3O0yEKUeGZCB5d3ASNJVrV+bRwUrslW4JVsMTJRZV3RN9wN4K3Ir9S07YP9AKwhnpkYjn4YYELPEW7ATaJ5NOdJt9CVvDexUvA0yo,iv:oKofj8QczfgukfiwN1yJFoJkdvxbEG79sq8ftkmkpGw=,tag:RK63zgbMP9s260fVMlhhIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dzNiZ2JOalpLcjdaWnZR
            Q0pYNWVNL1FLSnU2elNxYzVsdTkwZ1QvMmtrCnVDY0hyUGpPbnR5UmlKcFIwNWJr
            dWlnR2V6MEJlSDdvQ3VkamM1QjlEUUkKLS0tIHI1bkE3N0dFbjh5d21BQytyajU5
            MGkrK2FWUEU3c0pJc29iSVNCQS9IZE0KQgx5Mg881gbSgk5krzKgPjx9iLHrlf9E
            NvTVQcGSjlWrhAoBpe6GAoM6vSTAJJvkgcL79lp0qJz94KqTdqt9lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T10:22:47Z"
    mac: ENC[AES256_GCM,data:/rMPckumt7G7pZKH6RvkLJ/SMoLej/jrFr4cE8nQGhchU5M/MQNPSXtO+M4HpgVloF95Qa4mO+heAju2U4AqZsnzJLsvBY3P9XU/BVfNbnOFhzNqxX37IshPqq4jX7uaD/0aRXHRvNh6UUrjOryRblxZ+FmZ9rPTiIVrLf8W4jo=,iv:UtbsBERVKsumKlBZRSGldZ50RAa6YjC09/6zkytr37U=,tag:3vQKJyPboJFXNW+201+CSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
