apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wyPxtaK5JseDU5ZgP2rPkYdU9VYiMGl/qHnGPgVmBEPegOl2Sf9dd4qHgQhE82JZ7DhC3YgFXDdGHINuLWv/OyH7A3JXaf1O6PqAfJuQkIaxWPWFJo9G9H/t9ZST83Fi7JMYvd1+MxonzwmKMbbOix9BKKpzYatsjKke5ZSItmPW6CDbyxInN7+zASxiihCjB7Hm/7Qiq4oHCfn7cINvNSZnLDnZy2LA+2He2J9yvp7Lf8ToIv0zKAGDfx9mflhHuARpaYr1wCTmyeqarrT3ftaCvwOV6cGi5I9J/AK44wpARvb49HeQwbmcFAwZJjCimIPlLUutOM/0zrouxeuYOHp6NZ+Rl16qqGxHZI92PSCnoD7dH/zD9iMVRCulqf7/,iv:lBLws93NejuSFxKbb0/yaao+CnFz2KMuGfJnWESI0L8=,tag:qPeTZKFyl2sOzqEbZam72Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:KZD4EAn0eCDAEvY4iMLQWGU3MS47wxs5+9K5AYUnQk2E+v0nl8MpwGXxMtpxS+qAZW34HYF8fU4J5rKsrEuNeZaTp7pYQgxG0OiODKoZC1rChqSzvlhPK22LUnjSkdskcC7cC8yAZRTjeRl/M0vLLyiS5Bp2cPYRO0Vmqj32ybWV8aYA9u5rqdvoQqX9fgeWgFFQYNva1hWBmtBoGt8Nvt+BEkDBpLewenxXUoW//L5KTt6KCgOwe6S1cyQ3RulvAx3oOBgGUAwReEWxHg==,iv:NBUDLzoOvB5tCuKk9Im49Hkt8/njUe6OVGVYPk6R6/4=,tag:18Zbuso2SQurRavrhQXXCw==,type:str]
    known_hosts: ENC[AES256_GCM,data:tKaD4D4kJJvZv9EVqVhnlx4S+zUTPL5ZCTSdxlL03xQjxZIT1RoW/EQIPJRxEwF5DquBxcpG90kbAFYbeNjrlogIw1isjWuvKlQL9E4X6lypIncPL31alLLuchpptm3L8+rd6JR/TLWJgqHiw57iGEd841onja2CXCafdxsY/gDhk3KwkPGStncRDlPiyeYrJa3DZmSh2a4MGWk9lFaERiIXGbApTPW9bUep,iv:zlAbaQD4EngiIAJjlr5Z4KdtByGimJw7aqFg8p5AqKU=,tag:lprM7BZoeChhARhI5gYtbg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOE1MTVJhRlhFdmt3Sml3
            TTNRd0ZuL1RmM1VuYStxQVRQK2dJV29nSDE0CnNTVFh4OWZQUWVZbTBvaW15dktO
            am5GcnJmME5LQlg0QU1LWW8yQjhSQjgKLS0tIGFQRmNYd1doQno2NDhhb2MzZHN6
            dkNBek9RbmR0bmwvV2pjMzVJdFFlckkKkJ9faQyQCsM+dvEuEdLquxIT4b6LLVZn
            GhWv1bkfOP3GhCYwa6VF34DJv94oM2Gc41QuSf09ibXIOIfO+sND7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T05:58:22Z"
    mac: ENC[AES256_GCM,data:ARVo+7dU1PP0jrnQPwq/hmrz/UjDVFkSkjR0g3JHKF7raAKheeKLMhui+T8zo5MVaMv6RFXXNCpd1cjGt2y6yRmqGOOkOI3o1ykafVl4JuZ9nY7nD/DbknBvPcdPvYvg4yohbPjrNMem6F9OptqxnC66Q17dByx25XjciAALFvw=,iv:xF7+lW6kfo6NUjm628VI/J2ytttGvtPf6PtViYy+uwY=,tag:7hQhTUMJiPQZ9zmu+CbqvQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
